[id]
name = content_hygiene
version = 0.2.0-beta

[ui]
is_visible = 1
label = Splunk Content Hygiene
supported_themes = light,dark

[launcher]
author = Leiter Consulting
description = Read-only inventory, dependency, ownership, and content hygiene analysis for Splunk.
version = 0.2.0-beta

[package]
check_for_updates = 0
id = content_hygiene

[install]
is_configured = 0
build = 17
